### ISSUE TITLE
Hiredis v1.0.0

### ISSUE THREAD

**Issue by michael-grunder** [redis/hiredis#807]
I'm creating this issue to keep track of progress toward our first official v1.0.0 release.

I think the following PRs should be merged before the release:

- [x] Proper OOM handling and allowing users to replace allocator (#800)
- [ ] Add licenses to every file (#799)
- [x] RESP3 verbatim string support (#805) 
- [ ] Better GNU conformance in Makefile (#806)
- [x] More flexible SSL API (#804, #813, #821)
- [x] RESP3 OOB Push support (#825, #841)
---
If there's time:

- [ ] Stop using reserved identifiers (#682)

Please comment here if there are other things you'd like to see in v1.0.0.

**Comment by carlosabalde** [comment]
I'd be great to have the entry point for explicit OpenSSL initialisation as described in https://github.com/redis/hiredis/issues/804.

**Comment by michael-grunder** [comment]
Closing, as v1.0.0 is released!
